version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
  
  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: DEMODB
      MYSQL_USER: DEMODB_Admin
      MYSQL_PASSWORD: demo
    volumes:
      - ./.shares/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 5002:8080

  exceptionless:
    image: exceptionless/exceptionless:6.1.0
    volumes:
      - ./.shares/exceptionless/data:/usr/share/elasticsearch/data
    ports:
      - 5001:80

  healthcheckui:
    image: xabarilcoding/healthchecksui
    ports:
      - 5000:80
    environment:
      - Logging:LogLevel:Default=Information
      - Logging:Loglevel:Microsoft=Warning
      - Logging:LogLevel:HealthChecks=Warning
      - HealthChecksUI:HealthChecks:0:Name=ClientApiService
      - HealthChecksUI:HealthChecks:0:Uri=http://clientapiservice/healthz
      - HealthChecksUI:HealthChecks:1:Name=ProvisioningApiService
      - HealthChecksUI:HealthChecks:1:Uri=http://provisioningapiservice/healthz
      - HealthChecksUI:HealthChecks:2:Name=PoCAdministrationApiService
      - HealthChecksUI:HealthChecks:2:Uri=http://administrationservice/healthz


  clientapiservice:
    image: ${DOCKER_REGISTRY-}services-clientapi
    build:
      context: ..
      dockerfile: Services.ClientAPI/Dockerfile
    ports:
    - 80:80
    environment:
      - EXCEPTIONLESS_URL=http://exceptionless:80
      - EXCEPTIONLESS_APIKEY=nkBXORItJVsXkarjdLvRrxI2u7sfmx9xHByjx9Kp
    depends_on:
      - exceptionless
      - redis
    volumes:
      - ./.shares/ClientApiService/log:/var/log/ClientApiervice

  provisioningapiservice:
    image: ${DOCKER_REGISTRY-}provisioningapiservice
    build:
      context: ..
      dockerfile: Services.ProvisioningAPI/Dockerfile
    ports:
    - 81:80
    environment:
      - EXCEPTIONLESS_URL=http://exceptionless:80
      - EXCEPTIONLESS_APIKEY=nkBXORItJVsXkarjdLvRrxI2u7sfmx9xHByjx9Kp
    depends_on:
      - exceptionless
      - redis
    volumes:
      - ./.shares/provisioningapiservice/log:/var/log/provisioningapiservice

  administrationservice:
    image: ${DOCKER_REGISTRY-}servicesadministration
    build:
      context: ..
      dockerfile: Services.Administration/Dockerfile
    ports:
    - 89:80
    environment:
      - EXCEPTIONLESS_URL=http://exceptionless:80
      - EXCEPTIONLESS_APIKEY=nkBXORItJVsXkarjdLvRrxI2u7sfmx9xHByjx9Kp
    depends_on:
      - exceptionless
      - redis
    volumes:
      - ./.shares/AdministrationService/log:/var/log/AdministrationService
